/*
 * To change this license header, choose License Headers in Project Properties. To change this
 * template file, choose Tools | Templates and open the template in the editor.
 */
package com.ivan.app.view;

import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.Timer;
import java.awt.Graphics;
import java.io.IOException;
import com.ivan.app.screenshare.NetworkReceiver;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author ivan
 */
public class DynamicShareScreenReceiverPanel extends javax.swing.JPanel {

    private static final Logger LOG = LogManager.getLogger(DynamicShareScreenReceiverPanel.class);

    private static final long serialVersionUID = 3064811163288249731L;

    private NetworkReceiver networkReceiver;
    private Timer timer;

    public DynamicShareScreenReceiverPanel(String host, int port) {
        initComponents();

        try {
            InetAddress address = InetAddress.getByName(host);
            this.networkReceiver = new NetworkReceiver(address, port);
        } catch (UnknownHostException e1) {
            LOG.error(e1);
        }

        this.timer = new Timer(1000 / 30, e -> {
            this.timerEvent();
        });
    }

    private void timerEvent() {

        this.repaint();
    }

    @Override
    public void addNotify() {
        super.addNotify();
        this.timer.start();
        try {
            networkReceiver.run();
        } catch (IOException e) {
            LOG.error(e);
        }
    }

    @Override
    public void removeNotify() {
        super.removeNotify();
        this.timer.stop();
        try {
            networkReceiver.close();
        } catch (IOException e) {
            LOG.error(e);
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (this.networkReceiver == null || this.networkReceiver.getShareImage() == null) {
            return;
        }

        g.drawImage(this.networkReceiver.getShareImage(), 0, 0, this);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
                        Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
                        Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
